language: generic

services:
  - docker

install:
  - docker build -t mcrbot .

script: 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker tag mcrbot $DOCKER_REPO:latest